// Shared helpers for the Cloudflare scripts. Runs wrangler from the server workspace.
import { spawn } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SERVER = join(ROOT, 'server');
export const TEMPLATE = join(SERVER, 'wrangler.toml');
/** Personal deploy config (database id, allowed email). Git-ignored. */
export const DEPLOY_CONFIG = join(SERVER, 'wrangler.deploy.toml');
const WRANGLER = join(ROOT, 'node_modules', '.bin', 'wrangler');

export function argValue(name) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

/** Run wrangler; output is shown live and also returned. stdin stays interactive. */
export function wrangler(args, { quiet = false } = {}) {
  return new Promise((resolve) => {
    const child = spawn(WRANGLER, args, {
      cwd: SERVER,
      stdio: ['inherit', 'pipe', 'pipe'],
      env: { ...process.env, FORCE_COLOR: '0' },
    });
    let out = '';
    const onData = (stream) => (d) => {
      out += d.toString();
      if (!quiet) stream.write(d);
    };
    child.stdout.on('data', onData(process.stdout));
    child.stderr.on('data', onData(process.stderr));
    child.on('close', (code) => resolve({ code: code ?? 1, out }));
  });
}

export function readDeployConfig() {
  return existsSync(DEPLOY_CONFIG) ? readFileSync(DEPLOY_CONFIG, 'utf8') : null;
}

export function writeDeployConfig({ databaseId, allowedEmails }) {
  let toml = readFileSync(TEMPLATE, 'utf8');
  toml = toml.replace(/database_id = "[^"]*"/, `database_id = "${databaseId}"`);
  toml = toml.replace(/\[vars\]\n/, `[vars]\nALLOWED_EMAILS = "${allowedEmails}"\n`);
  toml = `# Generated by scripts/deploy-cloudflare.mjs from wrangler.toml. Personal; not committed.\n${toml}`;
  writeFileSync(DEPLOY_CONFIG, toml);
}

export const EMAIL_RE = /^[^\s@"'\\;]+@[^\s@"'\\;]+\.[^\s@"'\\;]+$/;

export function fail(msg) {
  console.error(`\n✖ ${msg}`);
  process.exit(1);
}
